In [1]:
import numpy as np
import time

In [2]:
a = np.zeros(4);                  print(f'np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}')
a = np.zeros((4));                print(f'np.zeros(4,) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}')
a = np.random.random_sample(4);   print(f'np.random.random_sample(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}')

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4) :   a = [0.59865999 0.65887491 0.9752999  0.75246137], a shape = (4,), a data type = float64


In [3]:
a = np.arange(4.);                print(f'np.arange(4.) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}')
a = np.random.rand(4);            print(f'np.random.rand(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}')

np.arange(4.) :   a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4) :   a = [0.45356128 0.22431383 0.97477609 0.0329021 ], a shape = (4,), a data type = float64


In [4]:
a = np.array([5,4,3,2]);          print(f'np.array([5,4,3,2]) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}')
a = np.array([5.,4,3,2]);         print(f'np.array([5.,4,3,2]) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}')

np.array([5,4,3,2]) :   a = [5 4 3 2], a shape = (4,), a data type = int32
np.array([5.,4,3,2]) :  a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


In [5]:
a = np.arange(10)
print(a)

print(f'a[2].shape: {a[2].shape} a[2]   = {a[2]}')

print(f'a[-1] = {a[-1]}')

try:
    c = a[10]
except Exception as e:
    print('ERROR')
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]   = 2
a[-1] = 9
ERROR
index 10 is out of bounds for axis 0 with size 10


In [7]:
a - np.arange(10)
print(f"a         = {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1];     print("a[2:7:1] = ", c)

# access 3 elements separated by two 
c = a[2:7:2];     print("a[2:7:2] = ", c)

# access all elements index 3 and above
c = a[3:];        print("a[3:]    = ", c)

# access all elements below index 3
c = a[:3];        print("a[:3]    = ", c)

# access all elements
c = a[:];         print("a[:]     = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


In [8]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, -2, 3, 4])
print(f'Binary operators work element wise: {a + b}')

Binary operators work element wise: [0 0 6 8]


In [9]:
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


In [10]:
a = np.array([1,2,3,4])

b = 5 * a
print(f'b = 5 * a : {b}')

b = 5 * a : [ 5 10 15 20]


In [11]:
def my_dot_func(a, b):
    x = 0 
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x    

In [14]:
a = np.array([1,2,3,4])
b  = np.array([-1,4,3,2])
print(f'my_dot_func(a,b) = {my_dot_func(a,b)}')

my_dot_func(a,b) = 24


In [15]:
a = np.array([1,2,3,4])
b  = np.array([-1,4,3,2])
c = np.dot(a,b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")


NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


In [16]:
np.random.seed(1)
a = np.random.rand(100000000)
b = np.random.rand(100000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()
c = my_dot_func(a,b)
toc = time.time()

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b) 

np.dot(a, b) =  25000669.8073
Vectorized version duration: 77.8894 ms 
my_dot(a, b) =  25000669.8073
loop version duration: 33962.0552 ms 


In [24]:
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

X[1] has shape (1,)
w has shape (1,)
c has shape ()


In [28]:
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}, a = {a}")                     

a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}, a = {a}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.8582913]]


In [30]:
a = np.array([[5], [4], [3]]);   print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]); #into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


In [33]:
a = np.arange(6).reshape(-1, 2)
print(f'a.shape: {a.shape}, \na= {a}')

#access an element
print(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")

#access a row
print(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}, type(a[2])   = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int32'> Accessing an element returns a scalar

a[2].shape:   (2,), a[2]   = [4 5], type(a[2])   = <class 'numpy.ndarray'>


In [36]:
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")
      
#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")

a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array
